[package]
name = "Optirrigation"
version = "0.1.0"
edition = "2024" # Or other Rust edition

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Add your dependencies here, for example:
# rand = "0.8"